refactor: vc proposal.
trustbloc/vc-go pull request #17
Opened 2023-09-14 13:36 UTC by vkubiv

2023-09-14 14:20 UTC, Moopli commented on new/verifiable/new_credential.go
> +func (vc *Credential) Contents() *CredentialContents {
@vkubiv Since `Credential.Contents` returns a copy of the content data, we need another way to construct a `Credential` from `CredentialContents`.

If we want API users to always parse credentials into the `Credential` type, then the functions to parse/marshal `CredentialContents` could be private, but we still need the public method for `CredentialContents` -> `Credential`.

2023-09-15 11:40 UTC, vkubiv commented on new/verifiable/new_credential.go
> +func (vc *Credential) Contents() *CredentialContents {
yes, we definitely need this

2023-09-22 14:07 UTC, rolsonquadras approved these changes

2023-09-22 14:58 UTC, DRK3 commented on verifiable/credential.go
> +// TODO: maybe is should be named JWTEnvelope, some times it contains unsecured JWT.
Unresolved TODO?

2023-09-22 14:58 UTC, DRK3 commented on verifiable/credential.go
> +	// TODO: consider deep copy
Unresolved TODO?

2023-09-22 14:59 UTC, DRK3 commented on verifiable/credential.go
> +// ToJWTString returns jtw-vc as a jwt string. In the case of json-ld vc returns an error.
Typo - `jtw-vc`

2023-09-22 14:59 UTC, DRK3 commented on verifiable/credential.go
> +		return "", errors.New("in jwt form can be called only for jwt vc")
I don't understand this error message. Can you rewrite it?

2023-09-22 15:00 UTC, DRK3 commented on verifiable/credential.go
> +// ToUniversalForm returns vc in it natural form. For jwt-vc it is a jwt string. For json-ld vc it is a json object.
```suggestion
// ToUniversalForm returns vc in its natural form. For jwt-vc it is a jwt string. For json-ld vc it is a json object.
```

2023-09-22 15:02 UTC, DRK3 commented on verifiable/credential.go
>  		// TODO Validation mechanism will be changed after completing of #968 and #976
Are these issues still relevant? They seem to be referencing issue numbers in Aries, so we should remove them.

2023-09-22 15:03 UTC, DRK3 commented on verifiable/credential.go
> +	// TODO: docjsonld.ValidateJSONLDMap has bug that it modify contexts of input vcJSON. Fix in did-go
Unresolved TODO? What does this mean? Are you saying a fix is needed in the did-go repo for this?

2023-09-22 15:04 UTC, DRK3 commented on verifiable/credential.go
> +func serializeCredentialContents(vcc *CredentialContents, proofs []Proof) (JSONObject, error) { //nolint:funlen,gocyclo
Can this linter issues be addressed? If not (or it's unreasonable), can you leave a comment explaining why?

2023-09-22 15:06 UTC, DRK3 commented on verifiable/credential.go
> +// Other returns credential bytes
I think we should try to avoid having these sorts of TODOs sitting in the comments, since they cause confusion for the reader about what APIs to use.

2023-09-22 15:07 UTC, DRK3 commented on verifiable/credential.go
> +// MarshalAsJSONLD converts Verifiable Credential to JSON bytes ignoring that it is JWT.
Need to clarify what `ignoring that it is JWT` means.

2023-09-22 15:07 UTC, DRK3 commented on verifiable/credential_sdjwt.go
> +	//TODO: Should we include ld proofs into display credential? Original implementation included them.
Unresolved TODO

2023-09-22 15:08 UTC, DRK3 commented on verifiable/credential_sdjwt.go
> +	//TODO: maybe we need to return only CredentialContents not all credential?
Unresolved TODO

2023-09-22 15:08 UTC, DRK3 commented on verifiable/credential_sdjwt_test.go
> +			//vc.JWSEnvelope.SDJWTVersion = common.SDJWTVersionDefault
Commented out code?

2023-09-22 15:09 UTC, DRK3 commented on verifiable/presentation.go
> +	// TODO single value contexts should be compacted as part of Issue [#1730]
Remove Aries issue numbers (or at least link to them fully)

2023-09-22 15:10 UTC, DRK3 requested changes
Please see my comments. Note that my general comments about "TODO" lines in the code apply to all of them, even though I didn't write a comment for every single one

2023-09-22 16:25 UTC, Moopli commented on verifiable/credential.go
> +// TODO: maybe is should be named JWTEnvelope, some times it contains unsecured JWT.
I agree with the TODO, let's rename to JWTEnvelope

2023-09-22 18:45 UTC, Moopli commented on verifiable/credential_sdjwt.go
> +	//TODO: Should we include ld proofs into display credential? Original implementation included them.
TODO is a good point, we should probably exclude ld proofs.

2023-09-22 18:45 UTC, Moopli commented on verifiable/credential_sdjwt.go
> +	//TODO: maybe we need to return only CredentialContents not all credential?
We'll need to review usage of `CreateDisplayCredential`, and see if consumers would prefer `JSONObject` or `CredentialContents`. If both are needed, we can keep the `Credential` return type.

2023-09-22 18:45 UTC, Moopli commented on verifiable/credential_sdjwt_test.go
> +		// TODO: rewrite tests to not directly manipulate JWSEnvelope. And make JWSEnvelope private.
TODO for followup PR?

2023-09-22 18:45 UTC, Moopli commented on verifiable/data_integrity_proof.go
> +	// TODO: rewrite to use json object instead bytes presentation
TODO is for followup PR?

2023-09-22 18:45 UTC, Moopli commented on verifiable/presentation.go
> +			return nil, fmt.Errorf("serialize credentials to raw presintaiton: %w", err)
Typo: `presintaiton` -> `presentation`

2023-09-22 18:45 UTC, Moopli commented on presexch/definition.go
> +		credentialSrc, err := credentialWithFieldValues.MarshalAsJSONLD()
Wondering if it's worth refactoring presexch in the future, so this marshal to bytes isn't needed. This would require either:
A) Marshal to JSON bytes later, for limited disclosure (SD-JWT and BBS both use json libraries in the selective disclosure implementations in presexch)
B) refactor the limited disclosure code so it doesn't operate on json bytes. This would simplify some code, but also mean we need to look for different libraries to work with json paths but not on json byte data.

2023-09-23 05:31 UTC, vkubiv commented on verifiable/credential_sdjwt_test.go
> +		// TODO: rewrite tests to not directly manipulate JWSEnvelope. And make JWSEnvelope private.
yes

2023-09-23 05:31 UTC, vkubiv commented on verifiable/data_integrity_proof.go
> +	// TODO: rewrite to use json object instead bytes presentation
yes

2023-09-23 05:35 UTC, vkubiv commented on presexch/definition.go
> +		credentialSrc, err := credentialWithFieldValues.MarshalAsJSONLD()
Yes, there is a lot of room for improvement. Ideally, if we can avoid json bytes manipulation

2023-09-23 05:35 UTC, vkubiv commented on verifiable/credential.go
> +// TODO: review JWT and SDJWT implementation. Do not expose claims externally.
yes

2023-09-23 05:39 UTC, vkubiv commented on verifiable/credential.go
> +	// TODO: consider deep copy
Both ways, a shallow and a deep copy have their own pros and cons. We need to thing about this

2023-09-23 05:41 UTC, vkubiv commented on verifiable/credential.go
> +func ParseCredential(vcData []byte, opts ...CredentialOpt) (*Credential, error) { // nolint:funlen,gocyclo
The current PR is just the initial PR of refactoring VC. VC code is too big and has too many issues to be addressed in on shot.

2023-09-23 05:44 UTC, vkubiv commented on verifiable/credential.go
>  		// TODO Validation mechanism will be changed after completing of #968 and #976
yes, they are relevant. It is more of a question to Sudesh about how to deal with them. I think we will have some clean-up tasks to go thought all arise remnants.

2023-09-23 05:45 UTC, vkubiv commented on verifiable/credential.go
> +	// TODO: docjsonld.ValidateJSONLDMap has bug that it modify contexts of input vcJSON. Fix in did-go
The bug is in did-go, after it is fixed workaround can be removed from this code.

2023-09-23 05:47 UTC, vkubiv commented on verifiable/credential.go
> +func serializeCredentialContents(vcc *CredentialContents, proofs []Proof) (JSONObject, error) { //nolint:funlen,gocyclo
@Moopli  there is one problem, we need to clean up null, and empty arrays and strings. this is harder when we convert things to interface{}.

2023-09-23 05:50 UTC, vkubiv commented on verifiable/credential.go
> +func serializeCredentialContents(vcc *CredentialContents, proofs []Proof) (JSONObject, error) { //nolint:funlen,gocyclo
@DRK3 If you check the function code you will see that it is really straightforward. If you have an idea for a comment that we can write there, I would really appreciate it if you would put it on this PR comment.

2023-09-23 05:54 UTC, vkubiv commented on verifiable/credential.go
> +// Other returns credential bytes
I want to discuss this problem, and maybe we will come up with a better solution. It will be nice to have some small design sessions after this PR merge. This todos pin points weak points in the current code.

2023-09-23 06:12 UTC, vkubiv commented on verifiable/credential.go
> +func (vc *Credential) ToUniversalForm() (interface{}, error) {
It is used in Presentation
```go
		rp[vpFldCredential], err = mapSlice2(vp.credentials, func(c *Credential) (interface{}, error) {
			return c.ToUniversalForm()
		})
```

Technically Presentation is still in a verifiable package. But they are different things that actually not related to each other. I prefer that Presentation will use only the public interface of Credential. 

Also, the same things will be useful in VCS. There are Credentials often enveloped in external structures before marshaling. json.RawMessage does not always work well in that way. 

One of the possibilities is to not directly work with bytes in credentials. So remove MarshalJSON, and for parsing too not use bytes[] but instead get as input this universal object. Also, this allows us to get rid of that quote unQuote problem.

2023-09-23 06:17 UTC, vkubiv commented on verifiable/credential.go
> +// For jwt vc it will be jwt claims json object.
No, it really useful outside. Currently, it is used for presex.  But it will be used in VCS too. 

There is a lot of code that like vc.JWT = "", then marshal to bytes and unmarshal. ToRawJSON can simplify this code.

2023-09-23 06:20 UTC, vkubiv commented on verifiable/credential.go
> +func ParseCredential(vcData []byte, opts ...CredentialOpt) (*Credential, error) { // nolint:funlen,gocyclo
you can skip proof during parsing and then call proof check separately. But by default, it will try to check proof. 

We need separate these things, but I want to discuss design first

2023-09-23 19:08 UTC, DRK3 commented on verifiable/credential.go
> +func ParseCredential(vcData []byte, opts ...CredentialOpt) (*Credential, error) { // nolint:funlen,gocyclo
We should really avoid adding `nolint` statements, and if we do, there should be a good reason beside it. Or, if we don't see value in that particular linter, we just disable it repo-wide. My observation is that once a `nolint` for something like `funlen` or `gocyclo` is added, it tends to stay there forever. When people in the future work on the code, they rarely ever address it because "the nolint was already there", and so the functions continue getting longer and more complicated.

2023-09-23 19:33 UTC, DRK3 commented on verifiable/credential.go
> +func serializeCredentialContents(vcc *CredentialContents, proofs []Proof) (JSONObject, error) { //nolint:funlen,gocyclo
`nolint` markers are suspicious looking. They should be used sparingly, otherwise there's not much benefit from having those linters enabled in the first place. I find that, in general, addressing `funlen` and `gocyclo` linting failures leads to better code. If we do decide to add a `nolint` for `funlen` or `gocycle`, then the only valid justification I can think of for this is that reworking the code to avoid adding those two `nolint`s would actually make the code harder to understand (which I admit, does happen sometimes). When you say it's "straightforward" is that what you mean here?

There's actually a linter rule called [nolintlint](https://pkg.go.dev/github.com/golangci/golangci-lint/pkg/golinters/nolintlint) that forces the author to justify any `nolint` statements. We've had it enabled on some of our repos before - I think we should add it here too.

2023-09-23 19:46 UTC, DRK3 reviewed
My recommendation for the future when doing a refactoring is to try to break it up into smaller pieces, where you figure out how each of those smaller pieces should work before merging (perhaps by discussions during the code review process), rather than a larger "broad" refactor but with a lot of TODO comments. The chances that a TODO stays in the code forever once it's merged in is quite high (see the various multiple-year-old TODOs leftover from aries-framework-go for proof of this).

2023-09-25 05:21 UTC, vkubiv commented on verifiable/credential.go
> +func ParseCredential(vcData []byte, opts ...CredentialOpt) (*Credential, error) { // nolint:funlen,gocyclo
@rolsonquadras I want to address this nolint on other PR. This is too big already. I have an idea of how we can move out Proof check from this function in a way users do not forget to call it acidity. Should I do it in this PR or leave this nolint for now?

2023-09-25 05:26 UTC, vkubiv commented on verifiable/credential.go
> +func serializeCredentialContents(vcc *CredentialContents, proofs []Proof) (JSONObject, error) { //nolint:funlen,gocyclo
@DRK3 I think adding rule [nolintlint](https://pkg.go.dev/github.com/golangci/golangci-lint/pkg/golinters/nolintlint) will be a good task for you. @rolsonquadras what do you think?

2023-09-25 05:29 UTC, vkubiv commented on verifiable/credential.go
> +func serializeCredentialContents(vcc *CredentialContents, proofs []Proof) (JSONObject, error) { //nolint:funlen,gocyclo
@DRK3 if you have any idea how serializeCredentialContents can be refactored I really want to hear that, because I don't have any idea. This function just checks if values are not empty and if not sets them into the map.

2023-09-25 05:30 UTC, vkubiv commented on verifiable/credential.go
> +// MarshalAsJSONLD converts Verifiable Credential to JSON bytes ignoring that it is JWT.
done

2023-09-25 05:44 UTC, vkubiv commented on verifiable/credential_sdjwt.go
> +	//TODO: maybe we need to return only CredentialContents not all credential?
It has strange usage in VCS. Used to verify claims. need to check with VCS guys

2023-09-25 05:52 UTC, vkubiv commented on verifiable/credential.go
> +func ParseCredential(vcData []byte, opts ...CredentialOpt) (*Credential, error) { // nolint:funlen,gocyclo
@Moopli  I have an idea to return from ParseCredential not directly *Credential, but some ParsingResults. It will have two methods, SkipProofCheck, and CheckProof. People writing calling code will not be able to accidentally forget the proof check. 

Examples : 
` vc, err := ParseCredential(credBytes, {ValidationOpts}).SkipProof()` 
or
` vc, err := ParseCredential(credBytes, {ValidationOpts}).CheckProof({ProofCheckOpts})`

2023-09-25 05:53 UTC, vkubiv commented on verifiable/credential.go
> +	//checkEmbeddedProof(vcData, getEmbeddedProofCheckOpts(vcOpts))
done

2023-09-25 06:04 UTC, vkubiv commented on verifiable/credential.go
> +func ParseCredential(vcData []byte, opts ...CredentialOpt) (*Credential, error) { // nolint:funlen,gocyclo
We can go even further and move out validation too. 
Examples:

`vc, err := ParseCredential(credBytes).Validate({ValidationOpts}).CheckProof({ProofCheckOpts})`

`vc, err := ParseCredential(credBytes).SkipValidationAndProofcheck({ValidationOpts})`

2023-09-25 06:06 UTC, vkubiv commented on verifiable/credential.go
> +func ParseCredential(vcData []byte, opts ...CredentialOpt) (*Credential, error) { // nolint:funlen,gocyclo
@rolsonquadras What do you think?

2023-09-25 06:45 UTC, vkubiv commented on verifiable/credential.go
> +// TODO: maybe is should be named JWTEnvelope, some times it contains unsecured JWT.
done

2023-09-25 06:45 UTC, vkubiv commented on verifiable/credential.go
> +		return "", errors.New("in jwt form can be called only for jwt vc")
done

2023-09-25 06:49 UTC, vkubiv commented on verifiable/credential.go
>  		// TODO Validation mechanism will be changed after completing of #968 and #976
@sudeshrshetty is this TODO still relevant?

2023-09-25 06:50 UTC, vkubiv commented on verifiable/credential_sdjwt_test.go
> +			//vc.JWSEnvelope.SDJWTVersion = common.SDJWTVersionDefault
done

2023-09-25 13:51 UTC, Moopli commented on verifiable/credential.go
> +func ParseCredential(vcData []byte, opts ...CredentialOpt) (*Credential, error) { // nolint:funlen,gocyclo
I agree

2023-09-25 13:53 UTC, Moopli commented on verifiable/credential.go
> +func (vc *Credential) ToUniversalForm() (interface{}, error) {
Makes sense!

2023-09-25 13:56 UTC, DRK3 commented on verifiable/credential.go
> +func serializeCredentialContents(vcc *CredentialContents, proofs []Proof) (JSONObject, error) { //nolint:funlen,gocyclo
@vkubiv I looked at the code and I also can't find a clean way to break it up. This is a case where the `nolint` makes sense. My only suggestion, then, is to leave a brief comment explaining why.

2023-09-25 13:57 UTC, Moopli approved these changes

2023-09-25 13:57 UTC, DRK3 approved these changes

2023-09-25 14:47 UTC, merged